services:
  bangumiss:
    container_name: bangumiss
    build:
      context: .
      dockerfile: ./Bangumiss/Dockerfile
    env_file:
      - ./Bangumiss/.env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"